### PR TITLE
Add some constants for Min PHP version and WP version also a description in Rest Example

### PR DESCRIPTION
**Pull request by MikeiLL**
Feel free to comment.

### CODE REVIEW

**Comment by MikeiLL** [comment]
Cool. My pleasure. More to come, in time, I hope. I'm barely scratching the surface of the features you have included here.
To initialize the Rest Example, I added a `backend/RestInit.php` class. Does that seem like a sensible place to do it?

**Comment by Mte90** [comment]
Well backend is executed only for users on the admin dashboard so this depends on your needs.

**Comment by MikeiLL** [comment]
Well, I need to 

    1. pull in custom posts from a shortcode
    2. post to cpt from an external app

**Comment by Mte90** [comment]
Internals is the best place :-)

**Pull request merged**
