### PR TITLE
Introduce EditorConfig adherence in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
From #175

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Mte90! Works!

**Comment by Mte90** [comment]
Looking at the errors we need to exclude `license.txt` and a lot of other files to fix 😂

**Comment by szepeviktor** [comment]
> composer.json
>    02:01 ❌ invalid indent size: 3, expected: 4

This is Really-Really strange.

**Comment by szepeviktor** [comment]
> Looking at the errors we need to exclude `license.txt` and a lot of other files to fix 😂

Just add a section to .editorconfig file.

**Comment by Mte90** [comment]
> > composer.json
> > 02:01 x invalid indent size: 3, expected: 4
> 
> This is Really-Really strange.

I think that we can exclude composer.json as we are normalizing with another tool

**Comment by szepeviktor** [comment]
```ini
[license.txt]
indent_style = space
end_of_line = lf
```

**Comment by szepeviktor** [comment]
Why not simply fix it?  #179

**Comment by szepeviktor** [comment]
WordPress has the _tabs for *.txt_ rule as it expects Windows users to open text files with Notepad :)

**Comment by szepeviktor** [comment]
> exclude readme and composer

EditorConfig is a wild animal, it needs

```ini
[{LICENSE.txt,README.txt}]
```

**Comment by szepeviktor** [comment]
Please consider adding an indentation check to your Coding Standard.

This is my trio of tests

- syntax
- CS
- static analysis

and the newcomer, No0 is byte-checking :)

e.g. `LC_ALL=C.UTF-8 find . -type f -exec grep -PHn '[^ -~]' "{}" ";"˙`

**Comment by szepeviktor** [comment]
+ add euro sign, German, Hungarian, Finish and French alphabet
- exclude that SQL dump

`áÁäÄçÇéÉòÒöÖ€`

**Pull request merged**
